#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   This is a standard Gradle wrapper launcher script. It locates
#   gradle-wrapper.jar next to this script and delegates to it.
#   Regenerate the matching gradle-wrapper.jar locally with:
#       gradle wrapper --gradle-version 8.8
#   (requires network access, which this environment does not have).
#
##############################################################################

APP_HOME=$(cd "$(dirname "$0")" >/dev/null && pwd)
APP_NAME="Gradle"
CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

if [ ! -f "$CLASSPATH" ]; then
    echo "ERROR: $CLASSPATH not found." >&2
    echo "Run 'gradle wrapper --gradle-version 8.8' (with network access) to generate it," >&2
    echo "or install Gradle locally and run 'gradle' instead of './gradlew'." >&2
    exit 1
fi

JAVACMD="java"
if [ -n "$JAVA_HOME" ] && [ -x "$JAVA_HOME/bin/java" ]; then
    JAVACMD="$JAVA_HOME/bin/java"
fi

exec "$JAVACMD" $JAVA_OPTS $GRADLE_OPTS \
    "-Dorg.gradle.appname=$APP_NAME" \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain "$@"
